language: python
cache: pip
python:
- '3.4'
- '3.5'
- '3.6'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
script: python error404/default_tests.py
deploy:
  provider: pypi
  user: harens
  password:
    secure: iyT0zZr6FrqdYfiax0xEB/ytAQbaYFxpYXATDRqlMy629k1S5Fd0AXvpdPiXRaTW51Z3QYb+3JU8/X2rfjnNp2WXkOqvI4v6FrxU82kggEJpGGlMGMXct+FdW+zdiDgqT83rq6Rv1KACAU1fbaKwM/wkCogtsUS0PRCaQWMRQw7G8S8NO67RrtVXM9nDgPKT3enE+1W5K23L13t9zoo1OrgQidjmyzBJc6MhYwyLSD+7ka8f6gXBR5TNXmn8SIUblKfEQQjWcVQdlBQhlfBSxUffjnV2QsPBG21r0q+i6YA59LbAYmXVlmqSyGumrVps5hBe8orVIyg+lOYJZDWX62CtMJTrhCqZRcSfaATplSmpeR6ZOg8kfGdDwQCPBazaEsV5DGuViEG22Mi1gfvA/vm1seeWUjpu0ZXugYIiWsfHmxbihdELZLDGkGc5lXswKxxyzQJCF0G0MGhtNM3xt0GV+dXulchRBz/jb88ifDz8X7LWVy4LnG9MnwjHWOavHbXL1+evII1evtRLpH0txFa1bro8QjKPIHp1gL1PiMCCQwzO8GLEoE90GfTeSWQAvrTTKbsXFFBc8fombFRkKMON3tY8JdKLEXhR/Cq9Un2pLYTR4iPSPEjMDk3Q30tG6n9AgjOe4imAlOWl4I4ysp7vXkw35asHf9tg2KYfqSY=
  skip_cleanup: true
  on:
    tags: true
    python: 3.6
notifications:
  email:
    on_success: never
    on_failure: always
